Added required features for the clone
TedLivist/nytarticle pull request #1
Opened 2021-03-24 16:28 UTC by TedLivist

## The features included:
- aside tag for editors' picks
- navbar
- footer
- images
- page styling

## The following files are also included:
- index.html file - this contains the html elements
- style.css file - for styling the html file
- README file - for highlighting some description about the project

2021-03-24 20:13 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @TedLivist      ! :wave: :wave:

#### You have done well so far, Your project looks really good!  :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.
- - -

### **Recommended**

**General**
- [x] Please add a live link to your readme file.

**Section Specific requirements**
- [ ] Your navbar is missing the bottom borderline. Please add it.
 
- [ ] Some parts of the main content texts have fonts that are larger than what is on the page. I'll recommend using [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension tool to help with this.

- [ ] The theory of inflation's beginning paragraph should be black.
- [ ] The Editor's Picks section should be beside the paragraph with a short thank you note on it.

**Original**

![Screenshot (123)](https://user-images.githubusercontent.com/49621279/112376880-40854b00-8ca2-11eb-8134-b2faed96ba80.png)

- [ ] The copyright section below the footer should be black font. Certain parts of your page should be grey/black instead of orange.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-03-25 10:00 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations @TedLivist :tada: :clinking_glasses: 

_**Thank you for implementing the required changes by the previous reviewer**_

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

**Comment(s)**
- Kindly check the inline comments below and commit the changes before you merge.

Again, congratulations, you can merge to the default branch.
Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-03-25 10:00 UTC, teekaytech commented on index.html
> +    <img src="images/nyheader.jpg" alt="nyt-header">
The NY Times logo should be linked. i.e. use `<a>` tag to wrap the logo  (<a href="https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0" rel="nofollow noreferrer noopener" target="_blank">link to page</a>)

2021-03-25 10:00 UTC, teekaytech commented on index.html
> +            <a href="#"><div class="subscribe-text"><img src="images/chinese.jpg" alt=""></div></a>
Always give the `alt` attribute a descriptive value.

2021-03-25 11:11 UTC, TedLivist commented on index.html
> +    <img src="images/nyheader.jpg" alt="nyt-header">
Thanks for the review. I have corrected this

2021-03-25 11:11 UTC, TedLivist commented on index.html
> +            <a href="#"><div class="subscribe-text"><img src="images/chinese.jpg" alt=""></div></a>
I have corrected this also

2021-03-25 11:50 UTC, TedLivist commented
> # Status: Approved 🟢
> ### Congratulations @TedLivist 🎉 🥂
> _**Thank you for implementing the required changes by the previous reviewer**_
> 
> **This project has passed all the mandatory requirements 👏 It is therefore approved ✔️**
> 
> **Comment(s)**
> 
> * Kindly check the inline comments below and commit the changes before you merge.
> 
> Again, congratulations, you can merge to the default branch.
> Do not forget to fill the project completion form, as this is important for your weekly progress score.
> 
> **_Good luck with your next task._**
> 
> **Taofeek Olalere [Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
> **Happy Coding 😃**

Hello Taofeek, I am kinda confused with the project instructions.
The Pathwright Project instruction says we should not merge.

![dont-merge](https://user-images.githubusercontent.com/36542986/112468458-90c6e080-8d68-11eb-82dc-99c3e865316c.jpg)

Yet according to your review, I can now merge. I do not know which one of the guidelines to follow.

2021-03-25 12:23 UTC, teekaytech commented
> > # Status: Approved green_circle
> > ### Congratulations @TedLivist tada clinking_glasses
> > _**Thank you for implementing the required changes by the previous reviewer**_
> > **This project has passed all the mandatory requirements clap It is therefore approved heavy_check_mark**
> > **Comment(s)**
> > 
> > * Kindly check the inline comments below and commit the changes before you merge.
> > 
> > Again, congratulations, you can merge to the default branch.
> > Do not forget to fill the project completion form, as this is important for your weekly progress score.
> > **_Good luck with your next task._**
> > **Taofeek Olalere [Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
> > **Happy Coding smiley**
> 
> Hello Taofeek, I am kinda confused with the project instructions.
> The Pathwright Project instruction says we should not merge.
> 
> ![dont-merge](https://user-images.githubusercontent.com/36542986/112468458-90c6e080-8d68-11eb-82dc-99c3e865316c.jpg)
> 
> Yet according to your review, I can now merge. I do not know which one of the guidelines to follow.

Hi @TedLivist

Kindly give me some time to make some clarifications about the instruction. I'll get back to you soon.

2021-03-25 15:34 UTC, teekaytech commented
> > > # Status: Approved green_circle
> > > ### Congratulations @TedLivist tada clinking_glasses
> > > _**Thank you for implementing the required changes by the previous reviewer**_
> > > **This project has passed all the mandatory requirements clap It is therefore approved heavy_check_mark**
> > > **Comment(s)**
> > > 
> > > * Kindly check the inline comments below and commit the changes before you merge.
> > > 
> > > Again, congratulations, you can merge to the default branch.
> > > Do not forget to fill the project completion form, as this is important for your weekly progress score.
> > > **_Good luck with your next task._**
> > > **Taofeek Olalere [Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
> > > **Happy Coding smiley**
> > 
> > 
> > Hello Taofeek, I am kinda confused with the project instructions.
> > The Pathwright Project instruction says we should not merge.
> > ![dont-merge](https://user-images.githubusercontent.com/36542986/112468458-90c6e080-8d68-11eb-82dc-99c3e865316c.jpg)
> > Yet according to your review, I can now merge. I do not know which one of the guidelines to follow.
> 
> Hi @TedLivist
> 
> Kindly give me some time to make some clarifications about the instruction. I'll get back to you soon.

Hello @TedLivist 

I think there's a misunderstanding. The purpose of the message was to ask you not to merge before the PR was approved. Now that the PR is approved, I believe you can merge. I've reported the issue to the relevant channel and if it has not been fixed by now, the statement will be fixed soon.

Happy coding!

2021-03-25 16:37 UTC, TedLivist commented
> > > > # Status: Approved green_circle
> > > > ### Congratulations @TedLivist tada clinking_glasses
> > > > _**Thank you for implementing the required changes by the previous reviewer**_
> > > > **This project has passed all the mandatory requirements clap It is therefore approved heavy_check_mark**
> > > > **Comment(s)**
> > > > 
> > > > * Kindly check the inline comments below and commit the changes before you merge.
> > > > 
> > > > Again, congratulations, you can merge to the default branch.
> > > > Do not forget to fill the project completion form, as this is important for your weekly progress score.
> > > > **_Good luck with your next task._**
> > > > **Taofeek Olalere [Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
> > > > **Happy Coding smiley**
> > > 
> > > 
> > > Hello Taofeek, I am kinda confused with the project instructions.
> > > The Pathwright Project instruction says we should not merge.
> > > ![dont-merge](https://user-images.githubusercontent.com/36542986/112468458-90c6e080-8d68-11eb-82dc-99c3e865316c.jpg)
> > > Yet according to your review, I can now merge. I do not know which one of the guidelines to follow.
> > 
> > 
> > Hi @TedLivist
> > Kindly give me some time to make some clarifications about the instruction. I'll get back to you soon.
> 
> Hello @TedLivist
> 
> I think there's a misunderstanding. The purpose of the message was to ask you not to merge before the PR was approved. Now that the PR is approved, I believe you can merge. I've reported the issue to the relevant channel and if it has not been fixed by now, the statement will be fixed soon.
> 
> Happy coding!

Okay then. I will merge. Thanks for the feedback.

2021-03-25 16:38 UTC, merged